BookStore/BookStore/Controllers/AuthorController.cs
using BookStore.Data;
using BookStore.Models.Author;
using BookStore.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private IAuthorService _authorService;
        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }

        public IActionResult Index()
        {
            OverviewAuthorViewModel viewModel = new OverviewAuthorViewModel()
            {
                authors = _authorService.GetAllAuthors()
            };
            return View(viewModel);
        }
        public IActionResult AddAuthor()
        {
            return View();
        }
        public IActionResult EditAuthor(int Id)
        {
            EditAuthorViewModel viewModel = new EditAuthorViewModel()
            {
                EditAuthor = _authorService.GetById(Id)
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAuthor(Author author)
        {
            if (ModelState.IsValid)
            {
                _authorService.AddAuthor(author);
                return RedirectToAction("Index");
            }
            else
            {
                return View(author);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditAuthor(EditAuthorViewModel author)
        {
            if (ModelState.IsValid)
            {
                _authorService.UpdateAuthor(author.EditAuthor);
                return RedirectToAction("Index");
            }
            else
            {
                return View(author);
            }
        }
        [HttpPost]
        public IActionResult Index(int Id) 
        {
            _authorService.RemoveAuthor(Id);
            return RedirectToAction("Index");
        }
    }
}

BookStore/BookStore/Controllers/BookController.cs
using BookStore.Data;
using BookStore.Models.Author;
using BookStore.Models.Book;
using BookStore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private IBookService _BookService;
        private IAuthorService _AuthorService;
        private IGenreService _GenreService;
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public BookController(IBookService bookService, IAuthorService authorService, IGenreService genreService, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _BookService = bookService;
            _AuthorService = authorService;
            _GenreService = genreService;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index(OverviewBooksViewModel viewModel)
        {
            List<Book> books = _BookService.GetBySearch(viewModel.Search, viewModel.GenreId, viewModel.ByTitle, viewModel.ByAuthor, viewModel.ByIsbn).ToList();
            List<Book> booksWithInformation = new List<Book>();
            foreach (Book book in books)
            {
                book.Author = _AuthorService.GetById(book.AuthorID);
                book.Genre = _GenreService.GetById(book.GenreId);
                booksWithInformation.Add(book);
            }
            viewModel = new OverviewBooksViewModel()
            {
                AllBooks = booksWithInformation.ToList(),
                AllGenres = _GenreService.GetAllGenres()
            };
            return View(viewModel);
        }
        public IActionResult AddBook()
        {
            AddBookViewModel viewModel = new AddBookViewModel()
            {
                Authors = _AuthorService.GetAllAuthors(),
                Genres = _GenreService.GetAllGenres()
            };
            return View(viewModel);
        }
        public IActionResult DetailBook(int Id)
        {
            Book book = _BookService.GetById(Id);
            book.Author = _AuthorService.GetById(book.AuthorID);
            book.Genre = _GenreService.GetById(book.GenreId);
            DetailBookViewModel viewModel = new DetailBookViewModel()
            {
                DetailsBook = book
            };
            
            return View(viewModel);
        }
        public IActionResult EditBook(int Id)
        {
            EditBookViewModel viewModel = new EditBookViewModel()
            { 
                Authors = _AuthorService.GetAllAuthors(), 
                Genres = _GenreService.GetAllGenres(), 
                ToEditBook = _BookService.GetById(Id) 
            };
            return View(viewModel);
        }
        //public IActionResult Search(OverviewBooksViewModel viewModel)
        //{
        //    IEnumerable<Book> SearchResult = _BookService.GetBySearch(viewModel.Search, viewModel.GenreId, viewModel.ByTitle, viewModel.ByAuthor, viewModel.ByIsbn);
        //    viewModel.AllBooks = SearchResult;
        //    return View(viewModel);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy ="Admin")]
        public IActionResult EditBook(EditBookViewModel editBook)
        {
            if (ModelState.IsValid)
            {
                Book editedBook = new Book()
                {
                    Id = editBook.ToEditBook.Id,
                    Title = editBook.ToEditBook.Title,
                    Isbn13 = editBook.ToEditBook.Isbn13,
                    Pages = editBook.ToEditBook.Pages,
                    Format = editBook.ToEditBook.Format,
                    Price = editBook.ToEditBook.Price,
                    AuthorID = editBook.ToEditBook.AuthorID,
                    GenreId = editBook.ToEditBook.GenreId,
                    UniqueUrl = editBook.ToEditBook.UniqueUrl
                };
                if (editBook.ToEditBook.Image != null)
                {
                    string uniqueFileName = GetUniqueFileName(editBook.ToEditBook.Image.FileName);
                    string uploads = Path.Combine(_hostingEnvironment.WebRootPath, "img");
                    string filePath = Path.Combine(uploads, uniqueFileName);
                    editBook.ToEditBook.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                    editedBook.UniqueUrl = uniqueFileName;
                }
                _BookService.EditBook(editedBook);
                return RedirectToAction("Index");
            }
            else
            {
                return View(editBook);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddBook(AddBookViewModel book)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = GetUniqueFileName(book.AddBook.Image.FileName);
                string uploads = Path.Combine(_hostingEnvironment.WebRootPath, "img");
                string filePath = Path.Combine(uploads, uniqueFileName);
                book.AddBook.Image.CopyTo(new FileStream(filePath, FileMode.Create));

                Book newBook = new Book()
                {
                    Title = book.AddBook.Title,
                    Isbn13 = book.AddBook.Isbn13,
                    Pages = book.AddBook.Pages,
                    Price = book.AddBook.Price,
                    Format = book.AddBook.Format,
                    AuthorID = book.AddBook.AuthorID,
                    GenreId = book.AddBook.GenreId,
                    UniqueUrl = uniqueFileName
                };
                _BookService.AddBook(newBook);

                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
        }
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                      + "_"
                      + Guid.NewGuid().ToString().Substring(0, 4)
                      + Path.GetExtension(fileName);
        }
        //https://stackoverflow.com/questions/35379309/how-to-upload-files-in-asp-net-core/35385472#35385472
    }
}

BookStore/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" data-bs-toggle="dropdown">Authors</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="AddAuthor">New Author</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" data-bs-toggle="dropdown">Books</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="AddBook">New Book</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>